server:
  port: 8010
spring:
  application:
    name: image-service
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: gallery
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/images}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}